### ISSUE TITLE
Bug: showPageAtIndex:animated: will not invoke didMovePageToIndex

### ISSUE THREAD

**Issue by bigluck** [maxep/MXPagerView#1]
Hi @maxep ,

I think [MXPagerView on line 95](https://github.com/maxep/MXPagerView/blob/master/MXPagerView/MXPagerView.m#L95) can be removed.

This code have a wrong behaviour when invoked from `self.segmentedPager.pager.showPageAtIndex()` with a `transitionStyle` of type `.Scroll`.

**Comment by maxep** [comment]
Hi @bigluck 

I will have a look, but I'm quite busy.. can you explain your wrong behavior ?

**Comment by bigluck** [comment]
Yep. I'm having issues when I invoke:

`self.segmentedPager.pager.showPageAtIndex(1, animated: false)`

This will select the second tab in the `segmentedControl` and the second page become active, but when I rotate the device (from portrait to landscape) the first page become active.

Replacing:

```
        if(self.transitionStyle == MXPagerViewTransitionStyleTab) {
            [self didMovePageToIndex:index];
        }
```

With:

```
        [self didMovePageToIndex:index];
```

this issue disappear.
